//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TmkMuhendislik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminInfo()
        {
            this.News = new HashSet<News>();
        }
    
        public int A_Id { get; set; }
        public string A_Email { get; set; }
        public string A_Password { get; set; }
        public string A_Name { get; set; }
        public string A_Surname { get; set; }
        public string A_PhoneNumber { get; set; }
        public string A_CreateDate { get; set; }
        public string A_UpdateDate { get; set; }
        public string A_DeleteDate { get; set; }
        public Nullable<bool> A_Check { get; set; }
        public string A_Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
    }
}
